---
title: "Untitled"
author: "Lisa DeBruine"
date: "07/10/2021"
output: html_document
---

```{r setup, message=FALSE}
library(faux)
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
library(readr)
library(glue)
theme_set(theme_minimal())

list.files("R", full.names = T) %>% lapply(source) -> sink
```

 
## Project 

```{r}
random_project <- function(student_id,
                           moodle_id = student_id) {
  # set seed using student ID
  seed_from_string(student_id)
  
  # randomise condition and version labels
  cond_levels <- sample(list(c("A","B"), 
                             c("cond1", "cond2"), 
                             c("ctrl", "test")), 1) %>% unlist()
  vers_levels <- sample(list(c("V1","V2"), 
                             c(1, 2), 
                             c("easy", "hard")), 1) %>% unlist()
  
  # simulate subjects
  subjects <- make_subjects(cond_levels = cond_levels, vers_levels = vers_levels)
  
  # simulate questionnaires
  questions <- make_quest(subjects)
  
  # customise instructions
  instructions <- make_instructions(
    template = "instructions.md",
    factors = list(
      language = c("monolingual", "bilingual"), 
      condition = cond_levels, 
      version = vers_levels
    ),
    student_id = student_id,
    quest_n = ncol(questions) - 1
  )

  # write files to a new directory
  dir.create("projects", showWarnings = FALSE)
  dir <- glue::glue("projects/Participant_{moodle_id}_assignsubmission_file_")
  dir.create(dir, showWarnings = FALSE)
  #readr::write_csv(subjects, file.path(dir, "subjects.csv"))
  # split subjects into separate files
  for (c in 1:2) { for (v in 1:2) {
    filename <- glue::glue("{dir}/subjects_condition-{cond_levels[[c]]}_version-{vers_levels[[v]]}.csv")
    subjects %>%
      filter(condition == cond_levels[[c]], 
             version == vers_levels[[v]]) %>%
      select(-condition, -version) %>%
      readr::write_csv(filename)
  }}
  
  readr::write_csv(questions, file.path(dir, "questions.csv"))
  write(instructions, file.path(dir, "instructions.md"))
  
  return(dir)
}
```

```{r}
#random_project("test")
```


```{r}

students <- readxl::read_excel("~/ownCloudPsy/data_skills_msc/assessment_2021/assign_Your Personal Assessment Data.xlsx", skip = 3) %>%
  select(student_id = `ID number`,
         moodle_id = `Participant No`)

purrr::pmap(students, random_project) -> projects

```


